name: Odoo Multi-Version Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test_run:
    name: Test for Odoo ${{ matrix.odoo_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: test-${{ matrix.odoo_version }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        odoo_version: ["15.0", "16.0", "17.0", "18.0"]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        docker compose build --build-arg ODOO_VERSION=${{ matrix.odoo_version }}

    - name: Run Addons Tests
      run: |
        docker compose run --rm odoo-tests

    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.yml down --volumes --remove-orphans